# yaml-language-server: https://github.com/espanso/espanso/blob/dev/schemas/match.schema.json
# uses form_urls.csv to paste the link to the corresponding URL.

global_vars:
  - name: "urlcsv"
    type: echo
    params:
      echo: "$CONFIG/match/packages/form-list/0.2.0/form_urls.csv"

matches:
  - trigger: ":forms"
    replace: "{{form_url}}"
    vars:
      - name: form_names
        type: shell
        params:
          cmd: awk -F, '{print $1}' {{urlcsv}}
      - name: form1
        type: form
        params:
          layout: |
            get link to D65 form:
            [[choices]]
          fields:
            choices:
              type: list
              values: "{{form_names}}"
      - name: form_url
        type: shell
        params:
          cmd: awk -F, '$1 == "{{form1.choices}}" {print $2}' {{urlcsv}}
